# Generated by Django 5.2 on 2025-09-03 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kulupler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duyuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=150)),
                ('icerik', models.TextField()),
                ('yayin_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kulup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duyurular', to='kulupler.kulup')),
            ],
        ),
    ]
