# Generated by Django 5.2 on 2025-09-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duyurular', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duyuru',
            name='yayin_tarihi',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
