# Generated by Django 5.2 on 2025-09-03 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kulup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('kategori', models.CharField(max_length=50)),
                ('aciklama', models.TextField()),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('yonetici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yonettigi_kulupler', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
