# Generated by Django 5.2 on 2025-09-05 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kullanici',
        ),
    ]
