# Generated by Django 5.2 on 2025-09-06 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kullanicilar', '0002_delete_kullanici'),
        ('kulupler', '0002_alter_kulup_olusturulma_tarihi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Uyelik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('kulup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uyeler', to='kulupler.kulup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uyelikler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'kulup'], name='kullanicila_user_id_fc950e_idx')],
                'unique_together': {('user', 'kulup')},
            },
        ),
    ]
